// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: accounts.sql

package sqlcgen

import (
	"context"
	"time"
)

const getAccountById = `-- name: GetAccountById :one
SELECT account_id, item_id, name, mask, balance_available, balance_current, iso_currency_code, type, subtype, raw_json, created_at, last_synced_at, tracked FROM accounts WHERE account_id = ? AND item_id = ?
`

type GetAccountByIdParams struct {
	AccountID string `json:"account_id"`
	ItemID    string `json:"item_id"`
}

func (q *Queries) GetAccountById(ctx context.Context, arg GetAccountByIdParams) (Account, error) {
	row := q.db.QueryRowContext(ctx, getAccountById, arg.AccountID, arg.ItemID)
	var i Account
	err := row.Scan(
		&i.AccountID,
		&i.ItemID,
		&i.Name,
		&i.Mask,
		&i.BalanceAvailable,
		&i.BalanceCurrent,
		&i.IsoCurrencyCode,
		&i.Type,
		&i.Subtype,
		&i.RawJson,
		&i.CreatedAt,
		&i.LastSyncedAt,
		&i.Tracked,
	)
	return i, err
}

const getAllAccounts = `-- name: GetAllAccounts :many
SELECT account_id, item_id, name, mask, balance_available, balance_current, iso_currency_code, type, subtype, raw_json, created_at, last_synced_at, tracked FROM accounts WHERE tracked = 1 ORDER BY created_at DESC
`

func (q *Queries) GetAllAccounts(ctx context.Context) ([]Account, error) {
	rows, err := q.db.QueryContext(ctx, getAllAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Account{}
	for rows.Next() {
		var i Account
		if err := rows.Scan(
			&i.AccountID,
			&i.ItemID,
			&i.Name,
			&i.Mask,
			&i.BalanceAvailable,
			&i.BalanceCurrent,
			&i.IsoCurrencyCode,
			&i.Type,
			&i.Subtype,
			&i.RawJson,
			&i.CreatedAt,
			&i.LastSyncedAt,
			&i.Tracked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertAccount = `-- name: UpsertAccount :exec
INSERT INTO accounts (account_id, item_id, name, mask, type, subtype, balance_available, balance_current, iso_currency_code, tracked, last_synced_at, raw_json)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(account_id) DO UPDATE SET
  item_id = excluded.item_id,
  name = excluded.name,
  mask = excluded.mask,
  type = excluded.type,
  subtype = excluded.subtype,
  balance_available = excluded.balance_available,
  balance_current = excluded.balance_current,
  iso_currency_code = excluded.iso_currency_code,
  last_synced_at = COALESCE(excluded.last_synced_at, accounts.last_synced_at),
  raw_json = excluded.raw_json
WHERE excluded.last_synced_at IS NULL
   OR accounts.last_synced_at IS NULL
   OR excluded.last_synced_at > accounts.last_synced_at
`

type UpsertAccountParams struct {
	AccountID        string     `json:"account_id"`
	ItemID           string     `json:"item_id"`
	Name             string     `json:"name"`
	Mask             *string    `json:"mask"`
	Type             *string    `json:"type"`
	Subtype          *string    `json:"subtype"`
	BalanceAvailable *float64   `json:"balance_available"`
	BalanceCurrent   *float64   `json:"balance_current"`
	IsoCurrencyCode  *string    `json:"iso_currency_code"`
	Tracked          int64      `json:"tracked"`
	LastSyncedAt     *time.Time `json:"last_synced_at"`
	RawJson          *string    `json:"raw_json"`
}

// Skip only when the incoming snapshot is provably older. Plaid omits
// last_updated_datetime for many institutions, so a NULL timestamp still
// means freshly fetched data and must not freeze the row.
func (q *Queries) UpsertAccount(ctx context.Context, arg UpsertAccountParams) error {
	_, err := q.db.ExecContext(ctx, upsertAccount,
		arg.AccountID,
		arg.ItemID,
		arg.Name,
		arg.Mask,
		arg.Type,
		arg.Subtype,
		arg.BalanceAvailable,
		arg.BalanceCurrent,
		arg.IsoCurrencyCode,
		arg.Tracked,
		arg.LastSyncedAt,
		arg.RawJson,
	)
	return err
}
