// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: bills.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const deactivateBillByID = `-- name: DeactivateBillByID :exec
UPDATE bills SET active = 0
WHERE id = ?1 AND user_id = ?2
`

type DeactivateBillByIDParams struct {
	ID     string `json:"id"`
	UserID string `json:"user_id"`
}

func (q *Queries) DeactivateBillByID(ctx context.Context, arg DeactivateBillByIDParams) error {
	_, err := q.db.ExecContext(ctx, deactivateBillByID, arg.ID, arg.UserID)
	return err
}

const deactivateBillByName = `-- name: DeactivateBillByName :execresult
UPDATE bills SET active = 0
WHERE user_id = ?1 AND UPPER(name) = UPPER(?2) AND active = 1
`

type DeactivateBillByNameParams struct {
	UserID string `json:"user_id"`
	Name   string `json:"name"`
}

func (q *Queries) DeactivateBillByName(ctx context.Context, arg DeactivateBillByNameParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deactivateBillByName, arg.UserID, arg.Name)
}

const insertBill = `-- name: InsertBill :exec
INSERT INTO bills (id, user_id, name, amount, day_of_month)
VALUES (?1, ?2, ?3, ?4, ?5)
`

type InsertBillParams struct {
	ID         string  `json:"id"`
	UserID     string  `json:"user_id"`
	Name       string  `json:"name"`
	Amount     float64 `json:"amount"`
	DayOfMonth int64   `json:"day_of_month"`
}

func (q *Queries) InsertBill(ctx context.Context, arg InsertBillParams) error {
	_, err := q.db.ExecContext(ctx, insertBill,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Amount,
		arg.DayOfMonth,
	)
	return err
}

const listActiveBillsByUser = `-- name: ListActiveBillsByUser :many
SELECT id, user_id, name, amount, day_of_month, active, created_at FROM bills
WHERE user_id = ?1 AND active = 1
ORDER BY day_of_month
`

func (q *Queries) ListActiveBillsByUser(ctx context.Context, userID string) ([]Bill, error) {
	rows, err := q.db.QueryContext(ctx, listActiveBillsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Bill{}
	for rows.Next() {
		var i Bill
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Amount,
			&i.DayOfMonth,
			&i.Active,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
