// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: daily_spend.sql

package sqlcgen

import (
	"context"
)

const deleteDailySpendByUser = `-- name: DeleteDailySpendByUser :exec
DELETE FROM daily_spend WHERE user_id = ?
`

func (q *Queries) DeleteDailySpendByUser(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteDailySpendByUser, userID)
	return err
}

const getDailySpendDay = `-- name: GetDailySpendDay :one
SELECT date, user_id, spend, ema_14, ema_28, ema_84 FROM daily_spend WHERE user_id = ? AND date = ?
`

type GetDailySpendDayParams struct {
	UserID string `json:"user_id"`
	Date   string `json:"date"`
}

func (q *Queries) GetDailySpendDay(ctx context.Context, arg GetDailySpendDayParams) (DailySpend, error) {
	row := q.db.QueryRowContext(ctx, getDailySpendDay, arg.UserID, arg.Date)
	var i DailySpend
	err := row.Scan(
		&i.Date,
		&i.UserID,
		&i.Spend,
		&i.Ema14,
		&i.Ema28,
		&i.Ema84,
	)
	return i, err
}

const insertDailySpend = `-- name: InsertDailySpend :exec
INSERT INTO daily_spend (date, user_id, spend, ema_14, ema_28, ema_84)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertDailySpendParams struct {
	Date   string   `json:"date"`
	UserID string   `json:"user_id"`
	Spend  float64  `json:"spend"`
	Ema14  *float64 `json:"ema_14"`
	Ema28  *float64 `json:"ema_28"`
	Ema84  *float64 `json:"ema_84"`
}

func (q *Queries) InsertDailySpend(ctx context.Context, arg InsertDailySpendParams) error {
	_, err := q.db.ExecContext(ctx, insertDailySpend,
		arg.Date,
		arg.UserID,
		arg.Spend,
		arg.Ema14,
		arg.Ema28,
		arg.Ema84,
	)
	return err
}

const listDailySpendByUserSince = `-- name: ListDailySpendByUserSince :many
SELECT date, user_id, spend, ema_14, ema_28, ema_84 FROM daily_spend
WHERE user_id = ? AND date >= ?
ORDER BY date ASC
`

type ListDailySpendByUserSinceParams struct {
	UserID string `json:"user_id"`
	Date   string `json:"date"`
}

func (q *Queries) ListDailySpendByUserSince(ctx context.Context, arg ListDailySpendByUserSinceParams) ([]DailySpend, error) {
	rows, err := q.db.QueryContext(ctx, listDailySpendByUserSince, arg.UserID, arg.Date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DailySpend{}
	for rows.Next() {
		var i DailySpend
		if err := rows.Scan(
			&i.Date,
			&i.UserID,
			&i.Spend,
			&i.Ema14,
			&i.Ema28,
			&i.Ema84,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpendTransactionsByUser = `-- name: ListSpendTransactionsByUser :many
SELECT CAST(COALESCE(t.authorized_date, t.date) AS TEXT) AS date, t.amount, t.amort_end, t.category_primary
FROM transactions t
JOIN accounts a ON a.account_id = t.account_id
JOIN items i ON i.item_id = a.item_id
WHERE i.user_id = ?
  AND t.excluded = 0
  AND t.removed_at IS NULL
  AND t.amount > 0
  AND a.tracked = 1
`

type ListSpendTransactionsByUserRow struct {
	Date            string  `json:"date"`
	Amount          float64 `json:"amount"`
	AmortEnd        *string `json:"amort_end"`
	CategoryPrimary string  `json:"category_primary"`
}

// The raw material for the daily-spend series: every transaction that counts
// against the user's budget. The authorized (swipe) date wins over the posted
// date when Plaid provides it: spend belongs to the day the card was used.
// Credits (amount < 0) stay out because deposits and refunds land in checking
// accounts and would swamp the spend signal. Untracked accounts are excluded
// so the tracked toggle means something once it gets a UI. (ASCII only: sqlc
// miscounts multibyte chars in comments and truncates the generated query.)
func (q *Queries) ListSpendTransactionsByUser(ctx context.Context, userID string) ([]ListSpendTransactionsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listSpendTransactionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSpendTransactionsByUserRow{}
	for rows.Next() {
		var i ListSpendTransactionsByUserRow
		if err := rows.Scan(
			&i.Date,
			&i.Amount,
			&i.AmortEnd,
			&i.CategoryPrimary,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
