// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: items.sql

package sqlcgen

import (
	"context"
)

const getAllItems = `-- name: GetAllItems :many
SELECT item_id, access_token, institution_name, status, cursor, created_at, last_synced_at FROM items WHERE status = 'active' ORDER BY created_at DESC
`

func (q *Queries) GetAllItems(ctx context.Context) ([]Item, error) {
	rows, err := q.db.QueryContext(ctx, getAllItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Item{}
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ItemID,
			&i.AccessToken,
			&i.InstitutionName,
			&i.Status,
			&i.Cursor,
			&i.CreatedAt,
			&i.LastSyncedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getItemByID = `-- name: GetItemByID :one
SELECT item_id, access_token, institution_name, status, cursor, created_at, last_synced_at FROM items WHERE item_id = ?
`

func (q *Queries) GetItemByID(ctx context.Context, itemID string) (Item, error) {
	row := q.db.QueryRowContext(ctx, getItemByID, itemID)
	var i Item
	err := row.Scan(
		&i.ItemID,
		&i.AccessToken,
		&i.InstitutionName,
		&i.Status,
		&i.Cursor,
		&i.CreatedAt,
		&i.LastSyncedAt,
	)
	return i, err
}
