// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql"
	"time"
)

type Account struct {
	AccountID        string          `json:"account_id"`
	ItemID           string          `json:"item_id"`
	Name             string          `json:"name"`
	Mask             sql.NullString  `json:"mask"`
	BalanceAvailable sql.NullFloat64 `json:"balance_available"`
	BalanceCurrent   sql.NullFloat64 `json:"balance_current"`
	IsoCurrencyCode  sql.NullString  `json:"iso_currency_code"`
	Type             sql.NullString  `json:"type"`
	Subtype          sql.NullString  `json:"subtype"`
	RawJson          sql.NullString  `json:"raw_json"`
	CreatedAt        time.Time       `json:"created_at"`
	LastSyncedAt     sql.NullTime    `json:"last_synced_at"`
}

type DailySpend struct {
	Date         string          `json:"date"`
	AccountID    string          `json:"account_id"`
	Spend        float64         `json:"spend"`
	SettledSpend float64         `json:"settled_spend"`
	Ema14        sql.NullFloat64 `json:"ema_14"`
	Ema28        sql.NullFloat64 `json:"ema_28"`
}

type Item struct {
	ItemID          string         `json:"item_id"`
	AccessToken     string         `json:"access_token"`
	InstitutionName sql.NullString `json:"institution_name"`
	Status          string         `json:"status"`
	Cursor          sql.NullString `json:"cursor"`
	CreatedAt       time.Time      `json:"created_at"`
	LastSyncedAt    sql.NullTime   `json:"last_synced_at"`
}

type Transaction struct {
	TransactionID    string         `json:"transaction_id"`
	AccountID        string         `json:"account_id"`
	Date             string         `json:"date"`
	Amount           float64        `json:"amount"`
	Name             sql.NullString `json:"name"`
	MerchantName     sql.NullString `json:"merchant_name"`
	CategoryPrimary  sql.NullString `json:"category_primary"`
	CategoryDetailed sql.NullString `json:"category_detailed"`
	PaymentChannel   sql.NullString `json:"payment_channel"`
	Pending          int64          `json:"pending"`
	RawJson          sql.NullString `json:"raw_json"`
}
