// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"time"
)

type Account struct {
	AccountID        string     `json:"account_id"`
	ItemID           string     `json:"item_id"`
	Name             string     `json:"name"`
	Mask             *string    `json:"mask"`
	BalanceAvailable *float64   `json:"balance_available"`
	BalanceCurrent   *float64   `json:"balance_current"`
	IsoCurrencyCode  *string    `json:"iso_currency_code"`
	Type             *string    `json:"type"`
	Subtype          *string    `json:"subtype"`
	RawJson          *string    `json:"raw_json"`
	CreatedAt        time.Time  `json:"created_at"`
	LastSyncedAt     *time.Time `json:"last_synced_at"`
	Tracked          int64      `json:"tracked"`
}

type DailySpend struct {
	Date   string   `json:"date"`
	UserID string   `json:"user_id"`
	Spend  float64  `json:"spend"`
	Ema14  *float64 `json:"ema_14"`
	Ema28  *float64 `json:"ema_28"`
	Ema84  *float64 `json:"ema_84"`
}

type Item struct {
	ItemID          string     `json:"item_id"`
	AccessToken     string     `json:"access_token"`
	InstitutionName *string    `json:"institution_name"`
	Status          string     `json:"status"`
	Cursor          *string    `json:"cursor"`
	CreatedAt       time.Time  `json:"created_at"`
	LastSyncedAt    *time.Time `json:"last_synced_at"`
	UserID          string     `json:"user_id"`
}

type Transaction struct {
	TxID               string  `json:"tx_id"`
	PlaidTxID          string  `json:"plaid_tx_id"`
	AccountID          string  `json:"account_id"`
	Date               string  `json:"date"`
	Amount             float64 `json:"amount"`
	Name               string  `json:"name"`
	MerchantName       *string `json:"merchant_name"`
	CategoryPrimary    string  `json:"category_primary"`
	CategoryDetailed   string  `json:"category_detailed"`
	CategoryConfidence *string `json:"category_confidence"`
	PaymentChannel     string  `json:"payment_channel"`
	Pending            int64   `json:"pending"`
	RemovedAt          *string `json:"removed_at"`
	AmortEnd           *string `json:"amort_end"`
	Excluded           int64   `json:"excluded"`
	RawJson            *string `json:"raw_json"`
	Notified           int64   `json:"notified"`
	AuthorizedDate     *string `json:"authorized_date"`
	TgMessageID        *int64  `json:"tg_message_id"`
	MessageStale       int64   `json:"message_stale"`
	MergeCandidateTxID *string `json:"merge_candidate_tx_id"`
	LogoUrl            *string `json:"logo_url"`
}

type User struct {
	ID                   string    `json:"id"`
	TgID                 *int64    `json:"tg_id"`
	TgUsername           *string   `json:"tg_username"`
	TgFirstName          *string   `json:"tg_first_name"`
	InviteCode           string    `json:"invite_code"`
	CanInvite            bool      `json:"can_invite"`
	Active               bool      `json:"active"`
	CreatedAt            time.Time `json:"created_at"`
	DiscretionaryMonthly *float64  `json:"discretionary_monthly"`
	ReportTime           *string   `json:"report_time"`
	ReportSentOn         *string   `json:"report_sent_on"`
}
