// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const adoptPendingTransaction = `-- name: AdoptPendingTransaction :execresult
UPDATE transactions SET
    plaid_tx_id = ?1,
    date = ?2,
    authorized_date = COALESCE(?3, authorized_date, date),
    amount = ?4,
    name = ?5,
    merchant_name = ?6,
    category_primary = ?7,
    category_detailed = ?8,
    category_confidence = ?9,
    payment_channel = ?10,
    pending = 0,
    removed_at = NULL,
    message_stale = 1,
    logo_url = COALESCE(?11, logo_url),
    raw_json = ?12
WHERE transactions.plaid_tx_id = ?13
  AND NOT EXISTS (SELECT 1 FROM transactions t2 WHERE t2.plaid_tx_id = ?1)
`

type AdoptPendingTransactionParams struct {
	PostedPlaidID      string  `json:"posted_plaid_id"`
	Date               string  `json:"date"`
	AuthorizedDate     *string `json:"authorized_date"`
	Amount             float64 `json:"amount"`
	Name               string  `json:"name"`
	MerchantName       *string `json:"merchant_name"`
	CategoryPrimary    string  `json:"category_primary"`
	CategoryDetailed   string  `json:"category_detailed"`
	CategoryConfidence *string `json:"category_confidence"`
	PaymentChannel     string  `json:"payment_channel"`
	LogoUrl            *string `json:"logo_url"`
	RawJson            *string `json:"raw_json"`
	PendingPlaidID     string  `json:"pending_plaid_id"`
}

// When a pending transaction settles, Plaid removes the pending row and sends
// the posted version under a new id, with pending_transaction_id pointing at
// the old one. Adopting rewrites the pending row in place instead of
// insert-plus-soft-delete: the internal tx_id survives, so chat message
// buttons, exclusions, spreads, and the notified flag all carry forward, and
// the pending row's date (the day the card was used) is preserved as the
// authorized date unless Plaid supplies a better one. The NOT EXISTS guard
// skips adoption when the posted id already has its own row; the caller
// falls back to a plain upsert. (ASCII-only comment: sqlc miscounts
// multibyte chars and truncates the generated query.)
func (q *Queries) AdoptPendingTransaction(ctx context.Context, arg AdoptPendingTransactionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, adoptPendingTransaction,
		arg.PostedPlaidID,
		arg.Date,
		arg.AuthorizedDate,
		arg.Amount,
		arg.Name,
		arg.MerchantName,
		arg.CategoryPrimary,
		arg.CategoryDetailed,
		arg.CategoryConfidence,
		arg.PaymentChannel,
		arg.LogoUrl,
		arg.RawJson,
		arg.PendingPlaidID,
	)
}

const adoptSettledTransactionByMatch = `-- name: AdoptSettledTransactionByMatch :execresult
UPDATE transactions SET
    plaid_tx_id = ?1,
    date = ?2,
    authorized_date = COALESCE(?3, authorized_date, date),
    amount = ?4,
    name = ?5,
    merchant_name = ?6,
    category_primary = ?7,
    category_detailed = ?8,
    category_confidence = ?9,
    payment_channel = ?10,
    pending = 0,
    removed_at = NULL,
    message_stale = 1,
    logo_url = COALESCE(?11, logo_url),
    raw_json = ?12
WHERE transactions.tx_id = (
    SELECT p.tx_id FROM transactions p
    WHERE p.pending = 1
      AND p.account_id = ?13
      AND p.amount = ?4
      AND COALESCE(p.authorized_date, p.date)
          BETWEEN date(CAST(?14 AS TEXT), '-7 days')
              AND CAST(?14 AS TEXT)
    ORDER BY COALESCE(p.authorized_date, p.date) DESC, p.tx_id ASC
    LIMIT 1
)
  AND NOT EXISTS (SELECT 1 FROM transactions t2 WHERE t2.plaid_tx_id = ?1)
`

type AdoptSettledTransactionByMatchParams struct {
	PostedPlaidID      string  `json:"posted_plaid_id"`
	Date               string  `json:"date"`
	AuthorizedDate     *string `json:"authorized_date"`
	Amount             float64 `json:"amount"`
	Name               string  `json:"name"`
	MerchantName       *string `json:"merchant_name"`
	CategoryPrimary    string  `json:"category_primary"`
	CategoryDetailed   string  `json:"category_detailed"`
	CategoryConfidence *string `json:"category_confidence"`
	PaymentChannel     string  `json:"payment_channel"`
	LogoUrl            *string `json:"logo_url"`
	RawJson            *string `json:"raw_json"`
	AccountID          string  `json:"account_id"`
	EffectiveDate      string  `json:"effective_date"`
}

// Fallback adoption for institutions that reissue pending transaction ids.
// A reissued pending can be created and settled between two of our syncs, so
// its add and remove collapse out of the stream: the settled transaction then
// names a pending id we never received, or carries none at all, and
// AdoptPendingTransaction has nothing to match. Instead of inserting a
// duplicate (which re-announces and strands the old row's spread/exclusions),
// claim the nearest unclaimed pending row on the same account with the same
// amount whose swipe date sits within a settlement window of the posted
// transaction's effective date. Nearest-date-first ordering keeps same-amount
// purchases on different days paired with the right settlement. Same SET list
// and posted-id guard as AdoptPendingTransaction. (ASCII-only comment: sqlc
// miscounts multibyte chars and truncates the generated query.)
func (q *Queries) AdoptSettledTransactionByMatch(ctx context.Context, arg AdoptSettledTransactionByMatchParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, adoptSettledTransactionByMatch,
		arg.PostedPlaidID,
		arg.Date,
		arg.AuthorizedDate,
		arg.Amount,
		arg.Name,
		arg.MerchantName,
		arg.CategoryPrimary,
		arg.CategoryDetailed,
		arg.CategoryConfidence,
		arg.PaymentChannel,
		arg.LogoUrl,
		arg.RawJson,
		arg.AccountID,
		arg.EffectiveDate,
	)
}

const backfillAuthorizedDate = `-- name: BackfillAuthorizedDate :exec
UPDATE transactions
SET authorized_date = (
    SELECT COALESCE(p.authorized_date, p.date)
    FROM transactions p WHERE p.plaid_tx_id = ?1
)
WHERE transactions.plaid_tx_id = ?2
  AND transactions.authorized_date IS NULL
`

type BackfillAuthorizedDateParams struct {
	PendingPlaidID string `json:"pending_plaid_id"`
	PostedPlaidID  string `json:"posted_plaid_id"`
}

// Recovery path for cursor replays: a resent settled transaction whose
// posted row already exists skips adoption, but its pending sibling may
// still be in the table (soft-deleted by the original settle). Lift that
// sibling's date into the posted row's empty authorized date. A missing
// sibling writes NULL over NULL, which is a no-op.
func (q *Queries) BackfillAuthorizedDate(ctx context.Context, arg BackfillAuthorizedDateParams) error {
	_, err := q.db.ExecContext(ctx, backfillAuthorizedDate, arg.PendingPlaidID, arg.PostedPlaidID)
	return err
}

const clearAmortEnd = `-- name: ClearAmortEnd :exec
UPDATE transactions SET amort_end = NULL WHERE tx_id = ?
`

func (q *Queries) ClearAmortEnd(ctx context.Context, txID string) error {
	_, err := q.db.ExecContext(ctx, clearAmortEnd, txID)
	return err
}

const clearMergeCandidate = `-- name: ClearMergeCandidate :exec
UPDATE transactions SET merge_candidate_tx_id = NULL WHERE tx_id = ?
`

func (q *Queries) ClearMergeCandidate(ctx context.Context, txID string) error {
	_, err := q.db.ExecContext(ctx, clearMergeCandidate, txID)
	return err
}

const clearMessageStale = `-- name: ClearMessageStale :exec
UPDATE transactions SET message_stale = 0 WHERE tx_id = ?
`

func (q *Queries) ClearMessageStale(ctx context.Context, txID string) error {
	_, err := q.db.ExecContext(ctx, clearMessageStale, txID)
	return err
}

const countPendingNotifications = `-- name: CountPendingNotifications :one
SELECT COUNT(*) FROM transactions
JOIN accounts ON accounts.account_id = transactions.account_id
JOIN items ON items.item_id = accounts.item_id
JOIN users ON users.id = items.user_id
WHERE users.tg_id = ? AND transactions.notified = 0 AND transactions.removed_at IS NULL
  AND transactions.amount >= 0 AND transactions.date >= CAST(?2 AS TEXT)
`

type CountPendingNotificationsParams struct {
	TgID   *int64 `json:"tg_id"`
	Cutoff string `json:"cutoff"`
}

func (q *Queries) CountPendingNotifications(ctx context.Context, arg CountPendingNotificationsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPendingNotifications, arg.TgID, arg.Cutoff)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteTransactionByTxID = `-- name: DeleteTransactionByTxID :exec
DELETE FROM transactions WHERE tx_id = ?
`

func (q *Queries) DeleteTransactionByTxID(ctx context.Context, txID string) error {
	_, err := q.db.ExecContext(ctx, deleteTransactionByTxID, txID)
	return err
}

const deleteTransactionsByItem = `-- name: DeleteTransactionsByItem :exec
DELETE FROM transactions WHERE account_id IN (SELECT account_id FROM accounts WHERE item_id = ?)
`

func (q *Queries) DeleteTransactionsByItem(ctx context.Context, itemID string) error {
	_, err := q.db.ExecContext(ctx, deleteTransactionsByItem, itemID)
	return err
}

const findTipRangeCandidate = `-- name: FindTipRangeCandidate :one
SELECT p.tx_id FROM transactions p
WHERE p.pending = 1
  AND p.account_id = ?1
  AND CAST(?2 AS REAL) > p.amount
  AND CAST(?2 AS REAL) <= p.amount * 1.5
  AND COALESCE(p.authorized_date, p.date)
      BETWEEN date(CAST(?3 AS TEXT), '-7 days')
          AND CAST(?3 AS TEXT)
ORDER BY COALESCE(p.authorized_date, p.date) DESC, p.tx_id ASC
LIMIT 1
`

type FindTipRangeCandidateParams struct {
	AccountID     string  `json:"account_id"`
	Amount        float64 `json:"amount"`
	EffectiveDate string  `json:"effective_date"`
}

// An unclaimed pending row that looks like the tip-adjusted original of a
// settled transaction: same account, swipe date within the settlement window,
// and the settled amount above the pending amount but within 1.5x of it -
// restaurant tips land here, while a gas-station $1 preauth against a $45
// settlement stays out and is left to fall off. Exact amounts never reach
// this query; they auto-adopt. The match is only recorded as an offer on the
// settled row; the user confirms from the chat card.
func (q *Queries) FindTipRangeCandidate(ctx context.Context, arg FindTipRangeCandidateParams) (string, error) {
	row := q.db.QueryRowContext(ctx, findTipRangeCandidate, arg.AccountID, arg.Amount, arg.EffectiveDate)
	var tx_id string
	err := row.Scan(&tx_id)
	return tx_id, err
}

const getPendingNotifications = `-- name: GetPendingNotifications :many
SELECT transactions.tx_id, transactions.plaid_tx_id, transactions.account_id, transactions.date, transactions.amount, transactions.name, transactions.merchant_name, transactions.category_primary, transactions.category_detailed, transactions.category_confidence, transactions.payment_channel, transactions.pending, transactions.removed_at, transactions.amort_end, transactions.excluded, transactions.raw_json, transactions.notified, transactions.authorized_date, transactions.tg_message_id, transactions.message_stale, transactions.merge_candidate_tx_id, transactions.logo_url FROM transactions
JOIN accounts ON accounts.account_id = transactions.account_id
JOIN items ON items.item_id = accounts.item_id
JOIN users ON users.id = items.user_id
WHERE users.tg_id = ? AND transactions.notified = 0 AND transactions.removed_at IS NULL
ORDER BY transactions.date ASC, transactions.tx_id ASC
LIMIT 50
`

type GetPendingNotificationsRow struct {
	Transaction Transaction `json:"transaction"`
}

func (q *Queries) GetPendingNotifications(ctx context.Context, tgID *int64) ([]GetPendingNotificationsRow, error) {
	rows, err := q.db.QueryContext(ctx, getPendingNotifications, tgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPendingNotificationsRow{}
	for rows.Next() {
		var i GetPendingNotificationsRow
		if err := rows.Scan(
			&i.Transaction.TxID,
			&i.Transaction.PlaidTxID,
			&i.Transaction.AccountID,
			&i.Transaction.Date,
			&i.Transaction.Amount,
			&i.Transaction.Name,
			&i.Transaction.MerchantName,
			&i.Transaction.CategoryPrimary,
			&i.Transaction.CategoryDetailed,
			&i.Transaction.CategoryConfidence,
			&i.Transaction.PaymentChannel,
			&i.Transaction.Pending,
			&i.Transaction.RemovedAt,
			&i.Transaction.AmortEnd,
			&i.Transaction.Excluded,
			&i.Transaction.RawJson,
			&i.Transaction.Notified,
			&i.Transaction.AuthorizedDate,
			&i.Transaction.TgMessageID,
			&i.Transaction.MessageStale,
			&i.Transaction.MergeCandidateTxID,
			&i.Transaction.LogoUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTransaction = `-- name: GetTransaction :one
SELECT tx_id, plaid_tx_id, account_id, date, amount, name, merchant_name, category_primary, category_detailed, category_confidence, payment_channel, pending, removed_at, amort_end, excluded, raw_json, notified, authorized_date, tg_message_id, message_stale, merge_candidate_tx_id, logo_url FROM transactions WHERE tx_id = ?
`

func (q *Queries) GetTransaction(ctx context.Context, txID string) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, getTransaction, txID)
	var i Transaction
	err := row.Scan(
		&i.TxID,
		&i.PlaidTxID,
		&i.AccountID,
		&i.Date,
		&i.Amount,
		&i.Name,
		&i.MerchantName,
		&i.CategoryPrimary,
		&i.CategoryDetailed,
		&i.CategoryConfidence,
		&i.PaymentChannel,
		&i.Pending,
		&i.RemovedAt,
		&i.AmortEnd,
		&i.Excluded,
		&i.RawJson,
		&i.Notified,
		&i.AuthorizedDate,
		&i.TgMessageID,
		&i.MessageStale,
		&i.MergeCandidateTxID,
		&i.LogoUrl,
	)
	return i, err
}

const listChatsWithPendingNotifications = `-- name: ListChatsWithPendingNotifications :many
SELECT DISTINCT users.tg_id FROM transactions
JOIN accounts ON accounts.account_id = transactions.account_id
JOIN items ON items.item_id = accounts.item_id
JOIN users ON users.id = items.user_id
WHERE users.tg_id IS NOT NULL AND transactions.notified = 0 AND transactions.removed_at IS NULL
`

func (q *Queries) ListChatsWithPendingNotifications(ctx context.Context) ([]*int64, error) {
	rows, err := q.db.QueryContext(ctx, listChatsWithPendingNotifications)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*int64{}
	for rows.Next() {
		var tg_id *int64
		if err := rows.Scan(&tg_id); err != nil {
			return nil, err
		}
		items = append(items, tg_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaleMessages = `-- name: ListStaleMessages :many
SELECT transactions.tx_id, transactions.plaid_tx_id, transactions.account_id, transactions.date, transactions.amount, transactions.name, transactions.merchant_name, transactions.category_primary, transactions.category_detailed, transactions.category_confidence, transactions.payment_channel, transactions.pending, transactions.removed_at, transactions.amort_end, transactions.excluded, transactions.raw_json, transactions.notified, transactions.authorized_date, transactions.tg_message_id, transactions.message_stale, transactions.merge_candidate_tx_id, transactions.logo_url FROM transactions
JOIN accounts ON accounts.account_id = transactions.account_id
JOIN items ON items.item_id = accounts.item_id
JOIN users ON users.id = items.user_id
WHERE users.tg_id = ? AND transactions.message_stale = 1
ORDER BY transactions.date ASC, transactions.tx_id ASC
LIMIT 50
`

type ListStaleMessagesRow struct {
	Transaction Transaction `json:"transaction"`
}

// Rows whose announcement card no longer matches the database: a pending
// settled via adoption, or a removed row (fell-off preauth) whose card gets
// struck through. Removed rows are deliberately included, unlike the notify
// queries. Rows with no recorded card just get the flag cleared.
func (q *Queries) ListStaleMessages(ctx context.Context, tgID *int64) ([]ListStaleMessagesRow, error) {
	rows, err := q.db.QueryContext(ctx, listStaleMessages, tgID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStaleMessagesRow{}
	for rows.Next() {
		var i ListStaleMessagesRow
		if err := rows.Scan(
			&i.Transaction.TxID,
			&i.Transaction.PlaidTxID,
			&i.Transaction.AccountID,
			&i.Transaction.Date,
			&i.Transaction.Amount,
			&i.Transaction.Name,
			&i.Transaction.MerchantName,
			&i.Transaction.CategoryPrimary,
			&i.Transaction.CategoryDetailed,
			&i.Transaction.CategoryConfidence,
			&i.Transaction.PaymentChannel,
			&i.Transaction.Pending,
			&i.Transaction.RemovedAt,
			&i.Transaction.AmortEnd,
			&i.Transaction.Excluded,
			&i.Transaction.RawJson,
			&i.Transaction.Notified,
			&i.Transaction.AuthorizedDate,
			&i.Transaction.TgMessageID,
			&i.Transaction.MessageStale,
			&i.Transaction.MergeCandidateTxID,
			&i.Transaction.LogoUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByUser = `-- name: ListTransactionsByUser :many
SELECT
    t.tx_id,
    CAST(COALESCE(t.authorized_date, t.date) AS TEXT) AS date,
    a.name AS account_name,
    COALESCE(t.merchant_name, t.name) AS description,
    t.amount,
    t.excluded,
    t.date AS raw_date,
    t.amort_end,
    t.logo_url
FROM transactions t
JOIN accounts a ON a.account_id = t.account_id
JOIN items i ON i.item_id = a.item_id
WHERE i.user_id = ?
  AND t.removed_at IS NULL
  AND a.tracked = 1
ORDER BY date DESC, t.tx_id DESC
`

type ListTransactionsByUserRow struct {
	TxID        string  `json:"tx_id"`
	Date        string  `json:"date"`
	AccountName string  `json:"account_name"`
	Description string  `json:"description"`
	Amount      float64 `json:"amount"`
	Excluded    int64   `json:"excluded"`
	RawDate     string  `json:"raw_date"`
	AmortEnd    *string `json:"amort_end"`
	LogoUrl     *string `json:"logo_url"`
}

// Feeds the /transactions table. Unlike ListSpendTransactionsByUser this
// includes credits and excluded rows: the table renders (and strikes
// through) exclusions rather than hiding them.
func (q *Queries) ListTransactionsByUser(ctx context.Context, userID string) ([]ListTransactionsByUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listTransactionsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTransactionsByUserRow{}
	for rows.Next() {
		var i ListTransactionsByUserRow
		if err := rows.Scan(
			&i.TxID,
			&i.Date,
			&i.AccountName,
			&i.Description,
			&i.Amount,
			&i.Excluded,
			&i.RawDate,
			&i.AmortEnd,
			&i.LogoUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markTransactionNotified = `-- name: MarkTransactionNotified :exec
UPDATE transactions SET notified = 1,
    tg_message_id = COALESCE(?1, tg_message_id)
WHERE tx_id = ?2
`

type MarkTransactionNotifiedParams struct {
	TgMessageID *int64 `json:"tg_message_id"`
	TxID        string `json:"tx_id"`
}

// Records the announcement outcome. tg_message_id is NULL when the send
// failed permanently; COALESCE keeps any previously recorded card in that
// case. message_stale is deliberately left alone: if an adoption landed
// between rendering the card and this write, the stale sweep still owes the
// card an edit.
func (q *Queries) MarkTransactionNotified(ctx context.Context, arg MarkTransactionNotifiedParams) error {
	_, err := q.db.ExecContext(ctx, markTransactionNotified, arg.TgMessageID, arg.TxID)
	return err
}

const markUnnotifiableTransactions = `-- name: MarkUnnotifiableTransactions :exec
UPDATE transactions SET notified = 1
WHERE notified = 0
  AND (amount < 0 OR removed_at IS NOT NULL OR date < CAST(?1 AS TEXT))
`

// Retire pending rows that will never be announced: credits, soft-deleted
// rows, and anything older than the notify window (cutoff is YYYY-MM-DD).
func (q *Queries) MarkUnnotifiableTransactions(ctx context.Context, cutoff string) error {
	_, err := q.db.ExecContext(ctx, markUnnotifiableTransactions, cutoff)
	return err
}

const mergeSettledIntoPending = `-- name: MergeSettledIntoPending :execresult
UPDATE transactions SET
    plaid_tx_id = ?1,
    date = ?2,
    authorized_date = COALESCE(?3, authorized_date, date),
    amount = ?4,
    name = ?5,
    merchant_name = ?6,
    category_primary = ?7,
    category_detailed = ?8,
    category_confidence = ?9,
    payment_channel = ?10,
    pending = 0,
    removed_at = NULL,
    message_stale = 1,
    logo_url = COALESCE(?11, logo_url),
    raw_json = ?12
WHERE transactions.tx_id = ?13
  AND transactions.pending = 1
  AND NOT EXISTS (SELECT 1 FROM transactions t2 WHERE t2.plaid_tx_id = ?1)
`

type MergeSettledIntoPendingParams struct {
	PostedPlaidID      string  `json:"posted_plaid_id"`
	Date               string  `json:"date"`
	AuthorizedDate     *string `json:"authorized_date"`
	Amount             float64 `json:"amount"`
	Name               string  `json:"name"`
	MerchantName       *string `json:"merchant_name"`
	CategoryPrimary    string  `json:"category_primary"`
	CategoryDetailed   string  `json:"category_detailed"`
	CategoryConfidence *string `json:"category_confidence"`
	PaymentChannel     string  `json:"payment_channel"`
	LogoUrl            *string `json:"logo_url"`
	RawJson            *string `json:"raw_json"`
	PendingTxID        string  `json:"pending_tx_id"`
}

// User-confirmed merge: fold a settled row's identity and values onto its
// pending sibling, keeping the pending row's tx_id (spread, exclusion, card).
// The caller deletes the settled row in the same database transaction first,
// so the unique plaid id is free to move. The amount is the settled one -
// that is the whole point of a tip merge. Guards mirror the adopt queries:
// the pending row must still be unclaimed and the posted id unused.
func (q *Queries) MergeSettledIntoPending(ctx context.Context, arg MergeSettledIntoPendingParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, mergeSettledIntoPending,
		arg.PostedPlaidID,
		arg.Date,
		arg.AuthorizedDate,
		arg.Amount,
		arg.Name,
		arg.MerchantName,
		arg.CategoryPrimary,
		arg.CategoryDetailed,
		arg.CategoryConfidence,
		arg.PaymentChannel,
		arg.LogoUrl,
		arg.RawJson,
		arg.PendingTxID,
	)
}

const setAmortEnd = `-- name: SetAmortEnd :exec
UPDATE transactions SET amort_end = date("date", CAST(?1 AS TEXT)) WHERE tx_id = ?2
`

type SetAmortEndParams struct {
	Modifier string `json:"modifier"`
	TxID     string `json:"tx_id"`
}

func (q *Queries) SetAmortEnd(ctx context.Context, arg SetAmortEndParams) error {
	_, err := q.db.ExecContext(ctx, setAmortEnd, arg.Modifier, arg.TxID)
	return err
}

const setExcluded = `-- name: SetExcluded :exec
UPDATE transactions SET excluded = ? WHERE tx_id = ?
`

type SetExcludedParams struct {
	Excluded int64  `json:"excluded"`
	TxID     string `json:"tx_id"`
}

func (q *Queries) SetExcluded(ctx context.Context, arg SetExcludedParams) error {
	_, err := q.db.ExecContext(ctx, setExcluded, arg.Excluded, arg.TxID)
	return err
}

const softDeleteTransaction = `-- name: SoftDeleteTransaction :exec
UPDATE transactions SET removed_at = datetime('now'), message_stale = 1
WHERE plaid_tx_id = ?
`

// Flags the card too: a removed row's announcement is now wrong (most often a
// pending that fell off - a preauth hold - without settling into its card),
// so the drain worker strikes the card through.
func (q *Queries) SoftDeleteTransaction(ctx context.Context, plaidTxID string) error {
	_, err := q.db.ExecContext(ctx, softDeleteTransaction, plaidTxID)
	return err
}

const upsertTransaction = `-- name: UpsertTransaction :one
INSERT INTO transactions (
    tx_id, plaid_tx_id, account_id, date, authorized_date, amount,
    name, merchant_name, category_primary, category_detailed, category_confidence,
    payment_channel, pending, raw_json, notified, merge_candidate_tx_id, logo_url
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(plaid_tx_id) DO UPDATE SET
    date = excluded.date,
    -- Plaid's authorized date wins when present, but a null must not clobber
    -- a date recovered via adoption: cursor replays resend all history with
    -- authorized_date null for institutions that never supply it.
    authorized_date = COALESCE(excluded.authorized_date, authorized_date),
    amount = excluded.amount,
    name = excluded.name,
    merchant_name = excluded.merchant_name,
    category_primary = excluded.category_primary,
    category_detailed = excluded.category_detailed,
    category_confidence = excluded.category_confidence,
    payment_channel = excluded.payment_channel,
    pending = excluded.pending,
    removed_at = NULL,
    raw_json = excluded.raw_json,
    -- A replay must not wipe an offer the user hasn't acted on, and a resend
    -- without enrichment must not wipe a logo we already have.
    merge_candidate_tx_id = COALESCE(excluded.merge_candidate_tx_id, merge_candidate_tx_id),
    logo_url = COALESCE(excluded.logo_url, logo_url)
RETURNING tx_id
`

type UpsertTransactionParams struct {
	TxID               string  `json:"tx_id"`
	PlaidTxID          string  `json:"plaid_tx_id"`
	AccountID          string  `json:"account_id"`
	Date               string  `json:"date"`
	AuthorizedDate     *string `json:"authorized_date"`
	Amount             float64 `json:"amount"`
	Name               string  `json:"name"`
	MerchantName       *string `json:"merchant_name"`
	CategoryPrimary    string  `json:"category_primary"`
	CategoryDetailed   string  `json:"category_detailed"`
	CategoryConfidence *string `json:"category_confidence"`
	PaymentChannel     string  `json:"payment_channel"`
	Pending            int64   `json:"pending"`
	RawJson            *string `json:"raw_json"`
	Notified           int64   `json:"notified"`
	MergeCandidateTxID *string `json:"merge_candidate_tx_id"`
	LogoUrl            *string `json:"logo_url"`
}

func (q *Queries) UpsertTransaction(ctx context.Context, arg UpsertTransactionParams) (string, error) {
	row := q.db.QueryRowContext(ctx, upsertTransaction,
		arg.TxID,
		arg.PlaidTxID,
		arg.AccountID,
		arg.Date,
		arg.AuthorizedDate,
		arg.Amount,
		arg.Name,
		arg.MerchantName,
		arg.CategoryPrimary,
		arg.CategoryDetailed,
		arg.CategoryConfidence,
		arg.PaymentChannel,
		arg.Pending,
		arg.RawJson,
		arg.Notified,
		arg.MergeCandidateTxID,
		arg.LogoUrl,
	)
	var tx_id string
	err := row.Scan(&tx_id)
	return tx_id, err
}
