// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package sqlcgen

import (
	"context"
)

const clearAmortEnd = `-- name: ClearAmortEnd :exec
UPDATE transactions SET amort_end = NULL WHERE tx_id = ?
`

func (q *Queries) ClearAmortEnd(ctx context.Context, txID string) error {
	_, err := q.db.ExecContext(ctx, clearAmortEnd, txID)
	return err
}

const getTransaction = `-- name: GetTransaction :one
SELECT tx_id, plaid_tx_id, account_id, date, amount, name, merchant_name, category_primary, category_detailed, category_confidence, payment_channel, pending, removed_at, amort_end, excluded, raw_json FROM transactions WHERE tx_id = ?
`

func (q *Queries) GetTransaction(ctx context.Context, txID string) (Transaction, error) {
	row := q.db.QueryRowContext(ctx, getTransaction, txID)
	var i Transaction
	err := row.Scan(
		&i.TxID,
		&i.PlaidTxID,
		&i.AccountID,
		&i.Date,
		&i.Amount,
		&i.Name,
		&i.MerchantName,
		&i.CategoryPrimary,
		&i.CategoryDetailed,
		&i.CategoryConfidence,
		&i.PaymentChannel,
		&i.Pending,
		&i.RemovedAt,
		&i.AmortEnd,
		&i.Excluded,
		&i.RawJson,
	)
	return i, err
}

const setAmortEnd = `-- name: SetAmortEnd :exec
UPDATE transactions SET amort_end = date("date", CAST(?1 AS TEXT)) WHERE tx_id = ?2
`

type SetAmortEndParams struct {
	Modifier string `json:"modifier"`
	TxID     string `json:"tx_id"`
}

func (q *Queries) SetAmortEnd(ctx context.Context, arg SetAmortEndParams) error {
	_, err := q.db.ExecContext(ctx, setAmortEnd, arg.Modifier, arg.TxID)
	return err
}

const setExcluded = `-- name: SetExcluded :exec
UPDATE transactions SET excluded = ? WHERE tx_id = ?
`

type SetExcludedParams struct {
	Excluded int64  `json:"excluded"`
	TxID     string `json:"tx_id"`
}

func (q *Queries) SetExcluded(ctx context.Context, arg SetExcludedParams) error {
	_, err := q.db.ExecContext(ctx, setExcluded, arg.Excluded, arg.TxID)
	return err
}

const softDeleteTransaction = `-- name: SoftDeleteTransaction :exec
UPDATE transactions SET removed_at = datetime('now')
WHERE plaid_tx_id = ?
`

func (q *Queries) SoftDeleteTransaction(ctx context.Context, plaidTxID string) error {
	_, err := q.db.ExecContext(ctx, softDeleteTransaction, plaidTxID)
	return err
}

const upsertTransaction = `-- name: UpsertTransaction :one
INSERT INTO transactions (
    tx_id, plaid_tx_id, account_id, date, amount,
    name, merchant_name, category_primary, category_detailed, category_confidence, 
    payment_channel, pending, raw_json
)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
ON CONFLICT(plaid_tx_id) DO UPDATE SET
    date = excluded.date,
    amount = excluded.amount,
    name = excluded.name,
    merchant_name = excluded.merchant_name,
    category_primary = excluded.category_primary,
    category_detailed = excluded.category_detailed,
    category_confidence = excluded.category_confidence,
    payment_channel = excluded.payment_channel,
    pending = excluded.pending,
    removed_at = NULL,
    raw_json = excluded.raw_json
RETURNING tx_id
`

type UpsertTransactionParams struct {
	TxID               string  `json:"tx_id"`
	PlaidTxID          string  `json:"plaid_tx_id"`
	AccountID          string  `json:"account_id"`
	Date               string  `json:"date"`
	Amount             float64 `json:"amount"`
	Name               string  `json:"name"`
	MerchantName       *string `json:"merchant_name"`
	CategoryPrimary    string  `json:"category_primary"`
	CategoryDetailed   string  `json:"category_detailed"`
	CategoryConfidence *string `json:"category_confidence"`
	PaymentChannel     string  `json:"payment_channel"`
	Pending            int64   `json:"pending"`
	RawJson            *string `json:"raw_json"`
}

func (q *Queries) UpsertTransaction(ctx context.Context, arg UpsertTransactionParams) (string, error) {
	row := q.db.QueryRowContext(ctx, upsertTransaction,
		arg.TxID,
		arg.PlaidTxID,
		arg.AccountID,
		arg.Date,
		arg.Amount,
		arg.Name,
		arg.MerchantName,
		arg.CategoryPrimary,
		arg.CategoryDetailed,
		arg.CategoryConfidence,
		arg.PaymentChannel,
		arg.Pending,
		arg.RawJson,
	)
	var tx_id string
	err := row.Scan(&tx_id)
	return tx_id, err
}
