// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const createInviteCode = `-- name: CreateInviteCode :exec
INSERT INTO users (
    id,
    tg_id,
    invite_code,
    active,
    can_invite
) VALUES (
    ?,
    NULL,
    ?,
    0,
    0
)
`

type CreateInviteCodeParams struct {
	ID         string `json:"id"`
	InviteCode string `json:"invite_code"`
}

func (q *Queries) CreateInviteCode(ctx context.Context, arg CreateInviteCodeParams) error {
	_, err := q.db.ExecContext(ctx, createInviteCode, arg.ID, arg.InviteCode)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = ?
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteUser, id)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, tg_id, tg_username, tg_first_name, invite_code, can_invite, active, created_at, discretionary_monthly FROM users WHERE id = ? and active = 1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TgID,
		&i.TgUsername,
		&i.TgFirstName,
		&i.InviteCode,
		&i.CanInvite,
		&i.Active,
		&i.CreatedAt,
		&i.DiscretionaryMonthly,
	)
	return i, err
}

const getUserByTelegram = `-- name: GetUserByTelegram :one
SELECT id, tg_id, tg_username, tg_first_name, invite_code, can_invite, active, created_at, discretionary_monthly FROM users WHERE tg_id = ? and active = 1
`

func (q *Queries) GetUserByTelegram(ctx context.Context, tgID *int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByTelegram, tgID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TgID,
		&i.TgUsername,
		&i.TgFirstName,
		&i.InviteCode,
		&i.CanInvite,
		&i.Active,
		&i.CreatedAt,
		&i.DiscretionaryMonthly,
	)
	return i, err
}

const listActiveUserIDs = `-- name: ListActiveUserIDs :many
SELECT id FROM users WHERE active = 1
`

func (q *Queries) ListActiveUserIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listActiveUserIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const redeemInviteCode = `-- name: RedeemInviteCode :execresult
UPDATE users
SET tg_id = ?, active = 1
WHERE invite_code = ? AND tg_id IS NULL
`

type RedeemInviteCodeParams struct {
	TgID       *int64 `json:"tg_id"`
	InviteCode string `json:"invite_code"`
}

func (q *Queries) RedeemInviteCode(ctx context.Context, arg RedeemInviteCodeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, redeemInviteCode, arg.TgID, arg.InviteCode)
}

const setDiscretionary = `-- name: SetDiscretionary :exec
UPDATE users SET discretionary_monthly = ? WHERE id = ?
`

type SetDiscretionaryParams struct {
	DiscretionaryMonthly *float64 `json:"discretionary_monthly"`
	ID                   string   `json:"id"`
}

func (q *Queries) SetDiscretionary(ctx context.Context, arg SetDiscretionaryParams) error {
	_, err := q.db.ExecContext(ctx, setDiscretionary, arg.DiscretionaryMonthly, arg.ID)
	return err
}
