// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlcgen

import (
	"context"
	"database/sql"
)

const createInviteCode = `-- name: CreateInviteCode :exec
INSERT INTO users (
    id,
    tg_id,
    invite_code,
    active,
    can_invite
) VALUES (
    ?,
    NULL,
    ?,
    0,
    0
)
`

type CreateInviteCodeParams struct {
	ID         string `json:"id"`
	InviteCode string `json:"invite_code"`
}

func (q *Queries) CreateInviteCode(ctx context.Context, arg CreateInviteCodeParams) error {
	_, err := q.db.ExecContext(ctx, createInviteCode, arg.ID, arg.InviteCode)
	return err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, tg_id, tg_username, tg_first_name, invite_code, can_invite, active, created_at FROM users WHERE id = ? and active = 1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TgID,
		&i.TgUsername,
		&i.TgFirstName,
		&i.InviteCode,
		&i.CanInvite,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByTelegram = `-- name: GetUserByTelegram :one
SELECT id, tg_id, tg_username, tg_first_name, invite_code, can_invite, active, created_at FROM users WHERE tg_id = ? and active = 1
`

func (q *Queries) GetUserByTelegram(ctx context.Context, tgID *int64) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByTelegram, tgID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.TgID,
		&i.TgUsername,
		&i.TgFirstName,
		&i.InviteCode,
		&i.CanInvite,
		&i.Active,
		&i.CreatedAt,
	)
	return i, err
}

const redeemInviteCode = `-- name: RedeemInviteCode :execresult
UPDATE users
SET tg_id = ?, active = 1
WHERE invite_code = ? AND tg_id IS NULL
`

type RedeemInviteCodeParams struct {
	TgID       *int64 `json:"tg_id"`
	InviteCode string `json:"invite_code"`
}

func (q *Queries) RedeemInviteCode(ctx context.Context, arg RedeemInviteCodeParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, redeemInviteCode, arg.TgID, arg.InviteCode)
}
