// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func LinkPage(linkToken string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<!doctype html><html><body><button id=\"link-btn\" data-token=\"")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		var templ_7745c5c3_Var2 string
		templ_7745c5c3_Var2, templ_7745c5c3_Err = templ.ResolveAttributeValue(linkToken)
		if templ_7745c5c3_Err != nil {
			return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/link.templ`, Line: 7, Col: 47}
		}
		_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ_7745c5c3_Var2)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "\">Link Account</button><p id=\"status\"></p><script src=\"https://cdn.plaid.com/link/v2/stable/link-initialize.js\"></script><script>\n\t\t\t\tconst btn = document.getElementById('link-btn');\n\t\t\t\tconst handler = Plaid.create({\n\t\t\t\t\ttoken: btn.dataset.token,\n\t\t\t\t\tonSuccess: async (publicToken, metadata) => {\n\t\t\t\t\t\tdocument.getElementById('status').textContent = 'Exchanging...';\n\t\t\t\t\t\tconst res = await fetch('/exchange-token', {\n\t\t\t\t\t\t\tmethod: 'POST',\n\t\t\t\t\t\t\theaders: {'Content-Type': 'application/json'},\n\t\t\t\t\t\t\tbody: JSON.stringify({public_token: publicToken})\n\t\t\t\t\t\t});\n\t\t\t\t\t\tdocument.getElementById('status').textContent = res.ok\n\t\t\t\t\t\t\t? 'Linked: ' + (metadata.institution?.name ?? 'account')\n\t\t\t\t\t\t\t: 'Failed';\n\t\t\t\t\t},\n\t\t\t\t\tonExit: (err) => {\n\t\t\t\t\t\tif (err) document.getElementById('status').textContent = err.display_message || 'Link exited with an error';\n\t\t\t\t\t}\n\t\t\t\t});\n\t\t\t\tbtn.addEventListener('click', () => handler.open());\n\t\t\t</script></body></html>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
