// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.1020
package templates

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

func initPlaidRelink(token string, itemID string) templ.ComponentScript {
	return templ.ComponentScript{
		Name: `__templ_initPlaidRelink_80de`,
		Function: `function __templ_initPlaidRelink_80de(token, itemID){const btn = document.getElementById('relink-button');
    const status = document.getElementById('status');
    const openLink = () => handler.open();
    const handler = Plaid.create({
        token: token,
        onSuccess: async () => {
            btn.removeEventListener('click', openLink);
            btn.disabled = true;
            btn.setAttribute('aria-busy', 'true');
            btn.textContent = 'reconnecting...';
            let ok = false;
            try {
                const res = await fetch('/relink-complete', {
                    method: 'POST',
                    headers: {'Content-Type': 'application/json'},
                    body: JSON.stringify({link_token: token, item_id: itemID})
                });
                ok = res.ok;
            } catch (_) {}
            btn.removeAttribute('aria-busy');
            if (ok) {
                btn.disabled = false;
                btn.textContent = 'go to your dashboard';
                btn.addEventListener('click', () => window.location.href = '/dashboard');
                status.textContent = 'reconnected — your transactions will sync shortly';
            } else {
                btn.textContent = 'reconnect failed';
                status.textContent = 'something went wrong — ask the bot for a fresh link';
            }
        },
        onExit: (err) => {
            if (err) status.textContent = err.display_message || 'link exited with an error';
        }
    });
    btn.addEventListener('click', openLink);
}`,
		Call:       templ.SafeScript(`__templ_initPlaidRelink_80de`, token, itemID),
		CallInline: templ.SafeScriptInline(`__templ_initPlaidRelink_80de`, token, itemID),
	}
}

func RelinkPage(linkToken string, itemID string, institution string) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Var2 := templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
			templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
			templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
			if !templ_7745c5c3_IsBuffer {
				defer func() {
					templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
					if templ_7745c5c3_Err == nil {
						templ_7745c5c3_Err = templ_7745c5c3_BufErr
					}
				}()
			}
			ctx = templ.InitializeContext(ctx)
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<article><h1>reconnect ")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			var templ_7745c5c3_Var3 string
			templ_7745c5c3_Var3, templ_7745c5c3_Err = templ.JoinStringErrs(institution)
			if templ_7745c5c3_Err != nil {
				return templ.Error{Err: templ_7745c5c3_Err, FileName: `templates/relink.templ`, Line: 44, Col: 35}
			}
			_, templ_7745c5c3_Err = templ_7745c5c3_Buffer.WriteString(templ.EscapeString(templ_7745c5c3_Var3))
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 2, "</h1><h3 class=\"pico-color-amber-200\">re-authenticate your account</h3><p>your bank connection needs to be refreshed. this usually happens when your bank credentials change (new password, security update, etc.).</p><p>tap the button below to securely re-authenticate through <a href=\"https://plaid.com\" target=\"_blank\"><span class=\"sc\">plaid</span></a>. your existing transaction history will be preserved.</p><button id=\"relink-button\">reconnect your bank</button><p id=\"status\"></p><script src=\"https://cdn.plaid.com/link/v2/stable/link-initialize.js\"></script>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = initPlaidRelink(linkToken, itemID).Render(ctx, templ_7745c5c3_Buffer)
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 3, "</article>")
			if templ_7745c5c3_Err != nil {
				return templ_7745c5c3_Err
			}
			return nil
		})
		templ_7745c5c3_Err = Layout("Reconnect Account").Render(templ.WithChildren(ctx, templ_7745c5c3_Var2), templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
